name: 'GitHub Actions Milk Bot'
 
on:
  push:
  schedule:
    - cron: '0 22 2,5,8,11,14,17,20,23,26,29 * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Send Message'
        run: curl https://sctapi.ftqq.com/${{secrets.SENDKEY}}.send\?title\=%E6%8B%BF%E7%89%9B%E5%A5%B6
